input_branches: # will be loaded from input ROOT files
  - pi1r_dz
  - pi2r_dz
  - pi3r_dz
  - mrho
  - deta12
  - dphi12 
  - deta23
  - dphi23 
  - deta31
  - dphi31 
  - weighteddR 
  - pi1r_pt
  - pi2r_pt
  - pi3r_pt
  - pi1r_doca2d
  - pi2r_doca2d
  - pi3r_doca2d
  - pi1r_doca2ds
  - pi2r_doca2ds
  - pi3r_doca2ds
  - pi1r_deta
  - pi2r_deta
  - pi3r_deta
  - pi1r_dphi
  - pi2r_dphi
  - pi3r_dphi
  - mpipi
  - vis_mass
  - dup_flag
  - w_1
  - evt
  - run

cont_features: # will be stored in the output foldfile as continuous features
  - pi1r_dz
  - pi2r_dz
  - pi3r_dz
  - mrho
  - deta12
  - dphi12 
  - deta23
  - dphi23 
  - deta31
  - dphi31 
  - weighteddR 
  - pi1r_pt
  - pi2r_pt
  - pi3r_pt
  - pi1r_doca2d
  - pi2r_doca2d
  - pi3r_doca2d
  - pi1r_doca2ds
  - pi2r_doca2ds
  - pi3r_doca2ds
  - pi1r_deta
  - pi2r_deta
  - pi3r_deta
  - pi1r_dphi
  - pi2r_dphi
  - pi3r_dphi
  - mpipi
  - vis_mass
cat_features: # will be stored in the output foldfile as categorical features
  - dup_flag
misc_features:
  - w_class_imbalance
  - evt
  - run