name: htt-ml
channels:
  - conda-forge
  - defaults
  - pytorch
  - plotly
dependencies:
  - python=3.9
  - pip
  - jupyterlab
  - mlflow
  - matplotlib
  - seaborn
  - plotly
  - numpy
  - numba
  - pandas
  - pytables
  - scipy
  - statsmodels
  - scikit-learn
  - lightgbm
  - pytorch
  - uproot
  - root
  - pip:
    - lumin
    - hydra-core
