name: htt-ml
channels:
  - conda-forge
  - defaults
  - pytorch
  - plotly
dependencies:
  - python=3.9
  - pip
  - jupyterlab=3.0
  - mlflow=1.19
  - matplotlib=3.2
  - seaborn=0.9
  - plotly=5.1
  - numpy=1.21
  - numba=0.53
  - pandas=1.3
  - pytables=3.6
  - scipy=1.7
  - statsmodels=0.12
  - scikit-learn=0.24
  - lightgbm=3.2
  - pytorch=1.8
  - uproot=4.0
  - root=6.24
  - pip:
    - lumin=0.7
    - hydra-core=1.1
    - wandb=0.12
    - kaleido
