name: htt-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=20.1
  - uproot=4.0
  - jupyterlab
  - pip:
    - jedi==0.17.2
    - lumin==0.7.2
    - matplotlib
    - numba
    - pandas
    - scikit-learn
    - scipy
    - seaborn
    - sklearn
    - statsmodels
    - torch
