input_branches: # will be loaded from input ROOT files
  - pt_1
  - pt_2
  - m_sv
  - m_vis
  - pt_tt
  - puppimet
  - njets
  - nbtag
  - jpt_1
  - jpt_2
  - bpt_1
  - bpt_2
  - jdeta
  - mjj
  - evt
  - run
  
cont_features: # will be stored in the output foldfile as continuous features
  - pt_1
  - pt_2
  - m_sv
  - m_vis
  - pt_tt
  - puppimet
  - jpt_1
  - jpt_2
  - bpt_1
  - bpt_2
  - jdeta
  - mjj
cat_features: # will be stored in the output foldfile as categorical features
  - njets
  - nbtag
misc_features: # will be stored in the output foldfile as miscellaneous features
  - evt
  - run
  - w_class_imbalance # see definition in preprocess.py