input_branches: # will be loaded from input ROOT files
  - pt_1
  - eta_1
  - pt_2
  - eta_2
  - m_sv
  - m_vis
  - pt_tt
  - dr_tt
  - puppimet
  - njets
  - nbtag
  - jpt_1
  - jeta_1
  - jcsv_1
  - jpt_2
  - jeta_2
  - jcsv_2
  - bpt_1
  - bcsv_1
  - bpt_2
  - bcsv_2
  - jdeta
  - dijetpt
  - mjj
  - mbb
  - dRbb
  - evt
  - run
  
cont_features: # will be stored in the output foldfile as continuous features
  - pt_1
  - eta_1
  - pt_2
  - eta_2
  - m_sv
  - m_vis
  - pt_tt
  - dr_tt
  - puppimet
  - jpt_1
  - jeta_1
  - jcsv_1
  - jpt_2
  - jeta_2
  - jcsv_2
  - bpt_1
  - bcsv_1
  - bpt_2
  - bcsv_2
  - jdeta
  - dijetpt
  - mjj
  - mbb
  - dRbb
cat_features: # will be stored in the output foldfile as categorical features
  - njets
  - nbtag
misc_features: # will be stored in the output foldfile as miscellaneous features
  - evt
  - run
  - w_class_imbalance # see definition in preprocess.py