for_training: False
compute_w_CP: False
defaults:
  - for_prediction/inputs@_global_: cp_htt
  - for_prediction/outputs@_global_: cp_htt
  - for_training/features@_global_: cp_htt

# override values
misc_features: # will be stored in the output foldfile as miscellaneous features
  - evt
