defaults:
  - ../preprocess/prediction_data@_global_.preprocess_cfg: lowpT_Taus.yaml
  - _self_

kind: 'for_datacards'

# mflow cfg
experiment_id: ???
run_id: ???

# input path & info
year: ???
orig_path: ${preprocess_cfg.input_path}
orig_filename_template: ${preprocess_cfg.input_filename_template}
orig_tree_name: ${preprocess_cfg.input_tree_name}
input_path: ${preprocess_cfg.output_path}
input_filename_template: ${preprocess_cfg.output_filename_template}.h5
sample_names: ${preprocess_cfg.input_samples}

# # output section
# misc_features: # will be added to output ROOT file along with prediction branches
#     - evt
#     - run
output_filename_template: '{sample_name}_pred.root'
output_tree_name: TauCheck
