kind: 'for_datacards'

# model & scaling pipe to make predictions
experiment_id: ???
run_id: ???

# input path & info
year: ???
orig_path: /nfs/dust/cms/user/rasp/storage/cardinia/${year}/InputDNNmt_June9-PAS
orig_filename_template: mt-NOMINAL_ntuple_{sample_name}_${year}.root
input_path: 'data/cp_htt/${year}/skims'
input_filename_template: '{sample_name}.hdf5'
sample_names:
    - Diboson
    - DYJets
    - EmbeddedMuTau
    - EWKZ
    - GluGluHToUncorrTauTau
    - HToWW
    - SingleMuon
    - TTbar
    - VBFHToUncorrTauTau
    - WHToUncorrTauTau
    - WJets
    - ZHToUncorrTauTau
misc_features: # will be added to output ROOT file along with prediction branches
    - evt
    - run

# output path & names
output_path: 'data/cp_htt/${year}/pred'
output_filename_template: 'mt-NOMINAL_ntuple_{sample_name}_${year}_pred.root'
output_tree_name: TauCheck
