kind: 'for_evaluation'

# input path & info
year: 2018
input_path: 'data/{year}/multi/skims'
input_filename_template: '{sample_name}.hdf5'
sample_names:
    - train
    - test

misc_features: # will be added to output ROOT file along with prediction branches
    - evt

# model & scaling pipe to make predictions
mlflow_experimentID: 1
mlflow_runID: 13e050761d8f40b69e2379b1c04da6ba

# output path & names
output_path: 'data/{year}/multi/pred'
output_filename_template: '{sample_name}_{year}_pred.csv'
