defaults:
  - ../preprocess@_global_.preprocess_cfg: prediction_data
  - _self_

kind: 'for_datacards'

# model & scaling pipe to make predictions
experiment_id: ???
run_id: ???

# input path & info
year: ???
orig_path: ${preprocess_cfg.input_path}
orig_filename_template: ${preprocess_cfg.input_filename_template}
input_path: 'data/bbH/${year}/skims/for_prediction'
input_filename_template: '{sample_name}.hdf5'
sample_names: ${preprocess_cfg.input_samples}

# output section
misc_features: # will be added to output ROOT file along with prediction branches
    - evt
    - run
output_filename_template: '{sample_name}_pred.root'
output_tree_name: TauCheck
