kind: 'for_evaluation'

# model & scaling pipe to make predictions
experiment_id: ???
run_id: ???

# input path & info
year: ???
input_path: 'data/bbH/${year}/skims/medium_wp'
input_filename_template: '{sample_name}.hdf5'
sample_names:
    - train
    - test

# output section
misc_features: # will be added to output file along with prediction branches
    - evt
    - gen_target
    - w_class_imbalance
output_filename_template: '{sample_name}.csv' # will log the files to corresponding mlflow run
