kind: 'for_evaluation'

# model & scaling pipe to make predictions
mlflow_experimentID: ???
mlflow_runID: ???

# input path & info
year: 2018
input_path: 'data/${year}/multi/skims'
input_filename_template: '{sample_name}.hdf5'
sample_names:
    - train
    - test

misc_features: # will be added to output file along with prediction branches
    - evt
    - gen_target
    - weight
    - class_weight
    - w_cp
    - w_class_imbalance

# output path & names
# will also log the files to corresponding mlflow run
output_path: 'data/${year}/multi/pred'
output_filename_template: '{sample_name}_${year}_pred.csv'
