experiment_id: ???
run_id: ???
dataset: ??? # name without csv extension

# plotting styles & class_id -> class_name mapping
class_to_info:
  0:
    name: tau_sig
    color: '194, 71, 92' # RGB format
    alpha: 0.6 # color transparency
    bin_size: 1e-2
  1:
    name: tau_bkg
    color: '163, 145, 113'
    alpha: 0.7
    bin_size: 1e-2
