year: 2018
input_path: /nfs/dust/cms/user/rasp/storage/cardinia/{year}/InputDNNmt_June9-PAS
process_to_cfg:
  ### signals
  ggH:
    filename: mt-NOMINAL_ntuple_GluGluHToUncorrTauTau_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5)'
    class: 0
  VBF:
    filename: mt-NOMINAL_ntuple_VBFHToUncorrTauTau_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5)'
    class: 0
  ZH:
    filename: mt-NOMINAL_ntuple_ZHToUncorrTauTau_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5)'
    class: 0
  WH:
    filename: mt-NOMINAL_ntuple_WHToUncorrTauTau_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5)'
    class: 0
  ### DY
  ZTT:
    filename: mt-NOMINAL_ntuple_DYJets_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_1==4) & (gen_match_2==5)'
    class: 1
  ZLL:
    filename: mt-NOMINAL_ntuple_DYJets_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_2!=6) & ((gen_match_1!=4) | (gen_match_2!=5))'
    class: 2
  ZJJ:
    filename: mt-NOMINAL_ntuple_DYJets_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_2 == 6)'
    class: 2
  ### ttbar
  TTT:
    filename: mt-NOMINAL_ntuple_TTbar_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_1==4) & (gen_match_2==5)'
    class: 1
  TTL:
    filename: mt-NOMINAL_ntuple_TTbar_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_2!=6) & ((gen_match_1!=4) | (gen_match_2!=5))'
    class: 2
  TTJ:
    filename: mt-NOMINAL_ntuple_TTbar_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_2 == 6)'
    class: 2
  ### Diboson
  VVT:
    filename: mt-NOMINAL_ntuple_Diboson_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_1==4) & (gen_match_2==5)'
    class: 1
  VVL:
    filename: mt-NOMINAL_ntuple_Diboson_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_2!=6) & ((gen_match_1!=4) | (gen_match_2!=5))'
    class: 2
  VVJ:
    filename: mt-NOMINAL_ntuple_Diboson_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_2 == 6)'
    class: 2
  ### Electroweak Z
  EWKZT:
    filename: mt-NOMINAL_ntuple_EWKZ_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_1==4) & (gen_match_2==5)'
    class: 1
  EWKZL:
    filename: mt-NOMINAL_ntuple_EWKZ_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_2!=6) & ((gen_match_1!=4) | (gen_match_2!=5))'
    class: 2
  EWKZJ:
    filename: mt-NOMINAL_ntuple_EWKZ_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5) & (gen_match_2 == 6)'
    class: 2
  ### misc
  WJets:
    filename: mt-NOMINAL_ntuple_WJets_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os>0.5)'
    class: 2
  QCD:
    filename: mt-NOMINAL_ntuple_SingleMuon_{year}.root
    cut: '(byMediumDeepTau2017v2p1VSjet_2>0.5) & (iso_1<0.15) & (os<0.5)'
    class: 2

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

tree_name: TauCheck
branches:
  - pt_1
  - pt_2
  - jpt_1
  - jpt_2
  - dijetpt
  - jdeta
  - njets
  - m_sv
  - mjj
  - m_vis
  - puppimt_1
  - pt_tt
  - puppimet

cont_features:
  - pt_1
  - pt_2
  - jpt_1
  - jpt_2
  - dijetpt
  - jdeta
  - m_sv
  - mjj
  - m_vis
  - puppimt_1
  - pt_tt
  - puppimet

cat_features:
  - njets

weight_name: weight
target_name: target

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

train_size: 0.8
norm: True
pca: False
weight_multiplier: 1.0
n_folds: 10

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

output_path: data/{year}/multi
train_name: 'train'
test_name: 'test'
pipe_name: 'input_pipe'
