year: 2018
process_to_file:
  ggH: /nfs/dust/cms/user/rasp/storage/cardinia/{year}/InputDNNmt_June9-PAS/mt-NOMINAL_ntuple_GluGluHToUncorrTauTau_{year}.root
  ZTT: /nfs/dust/cms/user/rasp/storage/cardinia/{year}/InputDNNmt_June9-PAS/mt-NOMINAL_ntuple_DYJets_{year}.root
process_to_class:
  ggH: 1
  ZTT: 0
process_to_cut:
  ggH: '(byMediumDeepTau2017v2p1VSjet_2 > 0.5) & (iso_1 < 0.15) & (os > 0.5)'
  ZTT: '(byMediumDeepTau2017v2p1VSjet_2 > 0.5) & (iso_1 < 0.15) & (os > 0.5) & (gen_match_1 == 4) & (gen_match_2 == 5)'

tree_name: TauCheck
branches:
  - pt_1
  - pt_2
  - jpt_1
  - jpt_2
  - dijetpt
  - jdeta
  - njets
  - m_fast
  - mjj
  - m_vis
  - puppimt_1
  - pt_tt
  - puppimet
cont_features:
  - pt_1
  - pt_2
  - jpt_1
  - jpt_2
  - dijetpt
  - jdeta
  - m_fast
  - mjj
  - m_vis
  - puppimt_1
  - pt_tt
  - puppimet
cat_features:
  - njets
weight_name: weight
target_name: target

train_size: 0.8
norm: True
pca: False
weight_multiplier: 1e3
n_folds: 10

output_folder: data
train_name: 'train'
test_name: 'test'
pipe_name: 'input_pipe'
