# path to the train/test data & scaling pipe
year: 2016
train_file: 'data/{year}/multi/skims/train.hdf5'
test_file: 'data/{year}/multi/skims/test.hdf5'
input_pipe_file: 'data/{year}/multi/skims/input_pipe.pkl'

# features to be used for training
cont_features:
  - pt_1
  - pt_2
  - jpt_1
  - jpt_2
  - dijetpt
  - jdeta
  - m_sv
  - mjj
  - m_vis
  - puppimt_1
  - pt_tt
  - puppimet
cat_features:
  - njets

# training weight
weight_name: 'w_cp'

# model parameters
model_param:
  objective: 'multiclass'
  num_class: 3
  metric: ['multi_logloss', 'multi_error']
  learning_rate: 0.1
  early_stopping: 10
  first_metric_only: True
  metric_freq: 10
  is_training_metric: True
  max_depth: 3
  bagging_fraction: 0.8
  bagging_freq: 5
  bagging_seed: 1357
  feature_fraction: 0.8
  num_threads: 4
  verbosity: 1
  seed: 1357
  num_iterations: 10

# plotting styles
class_to_info:
  0:
    name: higgs
    color: '194, 71, 92' # RGB format
    alpha: 0.6 # color transparency
  1:
    name: taus
    color: '90, 90, 90'
    alpha: 0.7
  2:
    name: fakes
    color: '65, 123, 159'
    alpha: .9
