train_file: 'data/train.hdf5'
test_file: 'data/test.hdf5'
pipe_file: 'data/input_pipe.pkl'

cont_features:
  - pt_1
  - pt_2
  - jpt_1
  - jpt_2
  - dijetpt
  - jdeta
  - m_fast
  - mjj
  - m_vis
  - puppimt_1
  - pt_tt
  - puppimet
cat_features:
  - njets

model_param:
  objective: 'binary'
  metric: ['auc', 'binary_error', 'binary_logloss']
  learning_rate: 0.01
  early_stopping: 10
  first_metric_only: True
  metric_freq: 10
  is_training_metric: True
  max_depth: 3
  bagging_fraction: 0.8
  bagging_freq: 5
  bagging_seed: 1357
  feature_fraction: 0.8
  num_threads: 4
  verbosity: 1
  seed: 1357
  num_iterations: 20
