for_training: False
compute_w_CP: False
defaults:
  - ../features@_global_: lowpT_Taus
  - _self_

# input section
year: ???
input_path: /nfs/dust/cms/user/puraniag/Notebooks/ # should be absolute path
input_filename_template: '{sample_name}.root' # assume the same pattern for all input sample files
input_tree_name: data_vars
input_samples:
  - vars

input_pipe_file: 'data/lowpT_Taus/${year}/skims/input_pipe.pkl' # relative path

# output section
output_path:  data/lowpT_Taus/${year}/skims/for_prediction # relative path
output_filename_template: '{sample_name}' # {sample_name} here will be filled with names from "input_samples" above
