defaults:
  - model@_global_: lowpT_Taus
  - features@_global_: lowpT_Taus
  - _self_

# path to the train/test data
year: ???
train_file: 'data/lowpT_Taus/${year}/skims/train.h5'
n_splits: 1 # will split training data into len(set(xtrain_split_feature % n_splits)) folds and train a separate model on each
xtrain_split_feature: 'evt' # used only if n_splits > 1; xtrain = cross-training
train_size: 0.9 # used only if n_splits=1, otherwise will use a left-out fold for testing

